import json
import subprocess
import sys

import pytest

from blue_firmament.model.openapi_generator import generate_models_from_openapi


@pytest.fixture()
def sample_openapi() -> dict:
    return {
        "components": {
            "schemas": {
                "Role": {
                    "type": "string",
                    "enum": ["admin", "user"],
                },
                "User": {
                    "type": "object",
                    "required": ["id", "name"],
                    "properties": {
                        "id": {"type": "integer"},
                        "name": {"type": "string"},
                        "roles": {
                            "type": "array",
                            "items": {"$ref": "#/components/schemas/Role"},
                        },
                        "manager": {"$ref": "#/components/schemas/User"},
                        "metadata": {"type": "object"},
                    },
                },
            }
        }
    }


def test_generate_models_from_openapi(sample_openapi):
    content = generate_models_from_openapi(sample_openapi)

    assert "class Role(enum.Enum):" in content
    assert "class User(BaseModel):" in content
    assert "roles: list[Role] | None = None" in content
    assert "manager: User | None = None" in content
    assert "metadata: dict[str, typing.Any] | None = None" in content


def test_cli_generates_file(tmp_path, sample_openapi):
    input_path = tmp_path / "openapi.json"
    output_path = tmp_path / "models.py"
    input_path.write_text(json.dumps(sample_openapi), encoding="utf-8")

    subprocess.run(
        [
            sys.executable,
            "-m",
            "blue_firmament.model.openapi_generator",
            "--input",
            str(input_path),
            "--output",
            str(output_path),
        ],
        check=True,
    )

    generated = output_path.read_text(encoding="utf-8")
    assert "class User(BaseModel):" in generated
    assert generated.startswith("# Generated by OpenAPIGenerator")
