"""Utilities to generate BFModel definitions from OpenAPI schemas.

This module provides a small code generator that reads an OpenAPI document
and converts ``components.schemas`` into ``BaseModel`` subclasses. The
result is plain Python code that can be committed to a repository or used in
CI to ensure generated models stay in sync with an upstream API definition.
"""

from __future__ import annotations

import argparse
import importlib
import importlib.util
import json
import pathlib
import typing
from typing import Mapping, MutableMapping

from . import BaseModel

SchemaT = Mapping[str, typing.Any]

_PRIMITIVE_TYPE_MAP: Mapping[str, str] = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
}


class OpenAPIGenerator:
    """Generate BFModel definitions from OpenAPI components.schemas."""

    def __init__(self, schemas: Mapping[str, SchemaT]):
        if not schemas:
            raise ValueError("OpenAPI document does not contain any schemas")
        self.schemas = dict(schemas)
        self.enum_schemas: dict[str, SchemaT] = {}
        self.model_schemas: dict[str, SchemaT] = {}
        self._categorize_schemas()

    def _categorize_schemas(self) -> None:
        for name, schema in self.schemas.items():
            if "enum" in schema:
                self.enum_schemas[name] = schema
            else:
                self.model_schemas[name] = schema

    def generate(self) -> str:
        parts = [
            "# Generated by OpenAPIGenerator",
            "from __future__ import annotations",
            "",
            "import typing",
            "import enum",
            "",
            "from blue_firmament.model import BaseModel",
            "",
        ]
        for name in sorted(self.enum_schemas):
            parts.extend(self._render_enum(name, self.enum_schemas[name]))
            parts.append("")

        for name in sorted(self.model_schemas):
            parts.extend(self._render_model(name, self.model_schemas[name]))
            parts.append("")

        return "\n".join(parts).rstrip() + "\n"

    def _render_enum(self, name: str, schema: SchemaT) -> list[str]:
        enum_values = schema.get("enum", [])
        if not isinstance(enum_values, list) or not enum_values:
            raise ValueError(
                f"Enum schema '{name}' must define a non-empty 'enum' list"
            )

        members = []
        for value in enum_values:
            member_name = str(value).upper().replace("-", "_").replace(" ", "_")
            members.append(f"    {member_name} = {value!r}")

        return [f"class {name}(enum.Enum):", *members]

    def _render_model(self, name: str, schema: SchemaT) -> list[str]:
        properties: MutableMapping[str, SchemaT] = typing.cast(
            MutableMapping[str, SchemaT], schema.get("properties", {})
        )
        required = set(schema.get("required", []))
        lines = [f"class {name}(BaseModel):"]

        if not properties:
            lines.append("    pass")
            return lines

        for prop, prop_schema in sorted(properties.items()):
            annotation = self._type_for_schema(prop_schema)
            default = ""
            if prop not in required:
                annotation = f"{annotation} | None"
                default_value = prop_schema.get("default", None)
                default = f" = {default_value!r}"
            lines.append(f"    {prop}: {annotation}{default}")

        return lines

    def _type_for_schema(self, schema: SchemaT) -> str:
        if "$ref" in schema:
            ref = typing.cast(str, schema["$ref"])
            return self._type_from_ref(ref)

        if "enum" in schema:
            inline_name = schema.get("title") or "InlineEnum"
            return inline_name

        type_name = schema.get("type")
        if type_name == "array":
            items = typing.cast(SchemaT, schema.get("items", {}))
            return f"list[{self._type_for_schema(items)}]"
        if type_name == "object":
            return "dict[str, typing.Any]"
        if type_name in _PRIMITIVE_TYPE_MAP:
            return _PRIMITIVE_TYPE_MAP[type_name]

        return "typing.Any"

    def _type_from_ref(self, ref: str) -> str:
        if not ref.startswith("#/components/schemas/"):
            raise ValueError(f"Unsupported $ref format: {ref}")
        return ref.split("/")[-1]


def load_openapi(path: pathlib.Path) -> Mapping[str, typing.Any]:
    """Load an OpenAPI document from ``path`` (JSON by default).

    YAML files are supported if PyYAML is installed in the environment.
    """

    raw = path.read_text(encoding="utf-8")
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        if importlib.util.find_spec("yaml") is None:  # pragma: no cover - optional dependency
            raise ValueError(
                "Failed to parse OpenAPI file as JSON and PyYAML is not installed"
            )

        yaml = importlib.import_module("yaml")  # type: ignore
        return typing.cast(Mapping[str, typing.Any], yaml.safe_load(raw))


def generate_models_from_openapi(openapi: Mapping[str, typing.Any]) -> str:
    components = openapi.get("components", {})
    schemas = components.get("schemas")
    if schemas is None:
        raise ValueError("OpenAPI document missing components.schemas")
    generator = OpenAPIGenerator(typing.cast(Mapping[str, SchemaT], schemas))
    return generator.generate()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate BFModel classes from OpenAPI components.schemas"
    )
    parser.add_argument(
        "--input", required=True, help="Path to an OpenAPI JSON or YAML document"
    )
    parser.add_argument(
        "--output", required=True, help="Path to write the generated Python module"
    )
    args = parser.parse_args(argv)

    openapi_doc = load_openapi(pathlib.Path(args.input))
    content = generate_models_from_openapi(openapi_doc)
    pathlib.Path(args.output).write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
